- name: fan0
  path: /system/chassis/motherboard/fan0
  methods:
    - type: tach
      sensors:
        - FAN1_REAR

- name: fan1
  path: /system/chassis/motherboard/fan1
  methods:
    - type: tach
      sensors:
        - FAN2_REAR

- name: fan2
  path: /system/chassis/motherboard/fan2
  methods:
    - type: tach
      sensors:
        - FAN3_REAR

- name: fan3
  path: /system/chassis/motherboard/fan3
  methods:
    - type: tach
      sensors:
        - FAN4_REAR
